version: '3'
services:
  flask_app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on: 
      - db
    restart: on-failure  # Add this line
    volumes:
      - S:\Uploads:/app/Uploads  # Add this line


  db:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '123qweasdzxcSq'
      MYSQL_DATABASE: 'elfateh'
    ports:
      - "3307:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
