version: '3.9'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./Uploads:/app/Uploads
    depends_on:
      - mysql

  mysql:
    container_name: mysql-db
    image: mysql:8.0
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123qweasdzxcSq
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - my_network

networks:
  my_network:
    external: true
