version: '3.9'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/files:/app/static/files

    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '123qweasdzxcSq'
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - my_network

networks:
  my_network:
    external: true
